export const CREATE_PAGE = 'CREATE_PAGE';
export const CREATE_PAGE_SUCCESS = 'CREATE_PAGE_SUCCESS';
export const CREATE_PAGE_FAILURE = 'CREATE_PAGE_FAILURE';
export const SET_LOADING = 'SET_LOADING_PAGE';
export const REMOVE_LOADING = 'REMOVE_LOADING_PAGE';
